[template.environment]
  CLIENT_NAME = "Shoreline Media Marketing"
  CUSTOM_LOGO = "//shorelinemedia.github.io/images/Shoreline-Media1.neuquant.png"
  PRIMARY_COLOR = "#0099CC"
  BG_COLOR = "#FFFF"
  UP_MESSAGE = "<p>We are upgrading our website.  We'll be back online shortly.</p>"
